name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          version: "latest"
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "bun"

      - run: bun install
      - run: bun run ci
